# Repository
repo_name: gl-inet/docs4.x
repo_url: https://github.com/gl-inet/docs4.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: GL.iNet
site_url: https://docs.gl-inet.com/en/4/
site_dir: /home/ubuntu/docs-build/en/4/
copyright: Copyright &copy; 2022 GL Technologies & Microuter Technologies

theme: 
  name: material
  logo: images/logo.svg
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.png

# Customization
extra:
  analytics:
    provider: google
    property: UA-108265653-5
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js

markdown_extensions:
  - attr_list
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.details

nav:
  - Home: index.md
  - User Guide:
    - Overview: user-guide/index.md
    - GL-AXT1800 (Slate AX):
      - Hardware Info: user-guide/gl-axt1800/hardware_info.md
      - First Time Setup: user-guide/gl-axt1800/first_time_setup.md
      - Internet: user-guide/gl-axt1800/internet.md
      - Wireless: user-guide/gl-axt1800/wireless.md
      - Clients: user-guide/gl-axt1800/clients.md
      - Upgrade: user-guide/gl-axt1800/upgrade.md
      - Firewall: user-guide/gl-axt1800/firewall.md
      - VPN: user-guide/gl-axt1800/vpn.md
      - Applications: user-guide/gl-axt1800/applications.md
      - More Settings: user-guide/gl-axt1800/more_settings.md
    - GL-AX1800 (Flint):
      - Hardware Info: user-guide/gl-ax1800/hardware_info.md
      - First Time Setup: user-guide/gl-ax1800/first_time_setup.md
      - Internet: user-guide/gl-ax1800/internet.md
      - Wireless: user-guide/gl-ax1800/wireless.md
      - Clients: user-guide/gl-ax1800/clients.md
      - Upgrade: user-guide/gl-ax1800/upgrade.md
      - Firewall: user-guide/gl-ax1800/firewall.md
      - VPN: user-guide/gl-ax1800/vpn.md
      - Applications: user-guide/gl-ax1800/applications.md
      - More Settings: user-guide/gl-ax1800/more_settings.md
  - Tutorials:
    - Overview: tutorials/index.md
    - General:
      - First time setup: tutorials/first_time_setup.md
      - Upgrade to latest firmware: tutorials/how_to_upgrade_to_the_latest_firmware.md
      - Check Firmware Version: tutorials/check_firmware_version.md
      - What is web Admin Panel: tutorials/web_admin_panel.md
    - Internet Connection:
      - Ethernet: tutorials/internet_ethernet.md
      - Repeater: tutorials/internet_repeater.md
      - Tethering: tutorials/internet_tethering.md
      - Cellular: tutorials/internet_cellular.md
      - Connect to a Hotspot with Captive Portal: tutorials/connect_to_a_hotspot_with_captive_portal.md
      - DHCP: tutorials/dhcp.md
      - PPPoE: tutorials/pppoe.md
      - Produce a wired connection: tutorials/produce_a_wired_connection.md
    - Wireless:
      - Wireless: tutorials/wireless.md
    - Clients:
      - Clients: tutorials/clients.md
    - Upgrade:
      - Frimware Upgrade: tutorials/firmware_upgrade.md
      - Download Firmware: tutorials/where_to_download_firmware.md
    - Firewall:
      - Firewall: tutorials/firewall.md
    - VPN:
      - VPN Dashboard: tutorials/vpn_dashboard.md
      - OpenVPN Client: tutorials/openvpn_client.md
      - OpenVPN Server: tutorials/openvpn_server.md
      - WireGuard Client: tutorials/wireguard_client.md
      - WireGuard Server: tutorials/wireguard_server.md
      - TCP or UDP: tutorials/openvpn_tcp_udp.md
      - Block No-VPN Traffic: tutorials/block_no_vpn_traffic.md
    - Applications:
      - Plug-ins: tutorials/plugins.md
      - Dynamic DNS: tutorials/ddns.md
      - GoodCloud: tutorials/cloud.md
      - AdGuardHOme: tutorials/adguardhome.md
      - Network Storage: tutorials/network_storage.md
      - Log: tutorials/log.md
    - More settings:
      - Change Admin Password: tutorials/admin_password.md
      - LAN: tutorials/lan.md
      - Time Zone: tutorials/time_zone.md
      - MAC Clone: tutorials/mac_clone.md
      - DNS: tutorials/dns.md
      - Network Mode: tutorials/network_mode.md
      - IPv6: tutorials/ipv6.md
      - Toggle Button Settings: tutorials/toggle_button_settings.md
      - Reset Firmware: tutorials/reset_firmware.md
      - Advanced Settings: tutorials/advanced_settings.md
    - Troubleshooting:
      - Debrick via Uboot: tutorials/uboot.md
    - Other:
      - Change WAN to LAN: tutorials/change_wan_to_lan.md
      - Mobile App: tutorials/mobile_app.md
      - Remote access web admin panel: tutorials/remote_access_web_admin_panel.md
      - Remote SSH to router: tutorials/remote_ssh_to_router.md
      - Check IP Address: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
      - Device id, MAC, SN: tutorials/where_to_find_the_device_id_mac_sn.md
  - Video Library:
    - Overview: video-library/index.md
  - Community:
    - Overview: community/index.md